### ISSUE TITLE
API for text styling?

### ISSUE THREAD

**Issue by CanadaHonk** [wintercg/proposal-cli-api#18]
Node is now shipping [their own API](https://github.com/nodejs/node/pull/51850) for this and many popular libraries offer this. We should decide if this is in scope or not first.

**Comment by Im-Beast** [comment]
There is already a standard for that – `%c` formatting specifier in `console`.
https://console.spec.whatwg.org/#formatting-specifiers

**Comment by CanadaHonk** [comment]
Closing in favor of above instead, can reopen if there are opinions otherwise
